version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      BING_API_KEY: ${BING_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENWEATHERMAP_API_KEY: ${OPENWEATHERMAP_API_KEY}
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev